// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: ozonmp/catalog_category_api/v1/catalog_category_api.proto

package catalog_category_api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on Category with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Category) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Foo

	return nil
}

// CategoryValidationError is the validation error returned by
// Category.Validate if the designated constraints aren't met.
type CategoryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CategoryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CategoryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CategoryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CategoryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CategoryValidationError) ErrorName() string { return "CategoryValidationError" }

// Error satisfies the builtin error interface
func (e CategoryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCategory.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CategoryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CategoryValidationError{}

// Validate checks the field values on CreateCategoryV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CreateCategoryV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetFoo()); l < 1 || l > 255 {
		return CreateCategoryV1RequestValidationError{
			field:  "Foo",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
	}

	return nil
}

// CreateCategoryV1RequestValidationError is the validation error returned by
// CreateCategoryV1Request.Validate if the designated constraints aren't met.
type CreateCategoryV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateCategoryV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateCategoryV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateCategoryV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateCategoryV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateCategoryV1RequestValidationError) ErrorName() string {
	return "CreateCategoryV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateCategoryV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateCategoryV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateCategoryV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateCategoryV1RequestValidationError{}

// Validate checks the field values on CreateCategoryV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CreateCategoryV1Response) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for CategoryId

	return nil
}

// CreateCategoryV1ResponseValidationError is the validation error returned by
// CreateCategoryV1Response.Validate if the designated constraints aren't met.
type CreateCategoryV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateCategoryV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateCategoryV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateCategoryV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateCategoryV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateCategoryV1ResponseValidationError) ErrorName() string {
	return "CreateCategoryV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateCategoryV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateCategoryV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateCategoryV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateCategoryV1ResponseValidationError{}

// Validate checks the field values on DescribeCategoryV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DescribeCategoryV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetCategoryId() <= 0 {
		return DescribeCategoryV1RequestValidationError{
			field:  "CategoryId",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// DescribeCategoryV1RequestValidationError is the validation error returned by
// DescribeCategoryV1Request.Validate if the designated constraints aren't met.
type DescribeCategoryV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribeCategoryV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribeCategoryV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribeCategoryV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribeCategoryV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribeCategoryV1RequestValidationError) ErrorName() string {
	return "DescribeCategoryV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e DescribeCategoryV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribeCategoryV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribeCategoryV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribeCategoryV1RequestValidationError{}

// Validate checks the field values on DescribeCategoryV1Response with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DescribeCategoryV1Response) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetValue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DescribeCategoryV1ResponseValidationError{
				field:  "Value",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// DescribeCategoryV1ResponseValidationError is the validation error returned
// by DescribeCategoryV1Response.Validate if the designated constraints aren't met.
type DescribeCategoryV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribeCategoryV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribeCategoryV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribeCategoryV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribeCategoryV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribeCategoryV1ResponseValidationError) ErrorName() string {
	return "DescribeCategoryV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DescribeCategoryV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribeCategoryV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribeCategoryV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribeCategoryV1ResponseValidationError{}

// Validate checks the field values on ListCategoriesV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListCategoriesV1Request) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// ListCategoriesV1RequestValidationError is the validation error returned by
// ListCategoriesV1Request.Validate if the designated constraints aren't met.
type ListCategoriesV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListCategoriesV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListCategoriesV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListCategoriesV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListCategoriesV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListCategoriesV1RequestValidationError) ErrorName() string {
	return "ListCategoriesV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListCategoriesV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListCategoriesV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListCategoriesV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListCategoriesV1RequestValidationError{}

// Validate checks the field values on ListCategoriesV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListCategoriesV1Response) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListCategoriesV1ResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// ListCategoriesV1ResponseValidationError is the validation error returned by
// ListCategoriesV1Response.Validate if the designated constraints aren't met.
type ListCategoriesV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListCategoriesV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListCategoriesV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListCategoriesV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListCategoriesV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListCategoriesV1ResponseValidationError) ErrorName() string {
	return "ListCategoriesV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListCategoriesV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListCategoriesV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListCategoriesV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListCategoriesV1ResponseValidationError{}

// Validate checks the field values on RemoveCategoryV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *RemoveCategoryV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetCategoryId() <= 0 {
		return RemoveCategoryV1RequestValidationError{
			field:  "CategoryId",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// RemoveCategoryV1RequestValidationError is the validation error returned by
// RemoveCategoryV1Request.Validate if the designated constraints aren't met.
type RemoveCategoryV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveCategoryV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveCategoryV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveCategoryV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveCategoryV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveCategoryV1RequestValidationError) ErrorName() string {
	return "RemoveCategoryV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveCategoryV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveCategoryV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveCategoryV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveCategoryV1RequestValidationError{}

// Validate checks the field values on RemoveCategoryV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *RemoveCategoryV1Response) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Found

	return nil
}

// RemoveCategoryV1ResponseValidationError is the validation error returned by
// RemoveCategoryV1Response.Validate if the designated constraints aren't met.
type RemoveCategoryV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveCategoryV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveCategoryV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveCategoryV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveCategoryV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveCategoryV1ResponseValidationError) ErrorName() string {
	return "RemoveCategoryV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveCategoryV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveCategoryV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveCategoryV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveCategoryV1ResponseValidationError{}
