// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package catalog_category_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CatalogCategoryApiServiceClient is the client API for CatalogCategoryApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogCategoryApiServiceClient interface {
	CreateCategoryV1(ctx context.Context, in *CreateCategoryV1Request, opts ...grpc.CallOption) (*CreateCategoryV1Response, error)
	DescribeCategoryV1(ctx context.Context, in *DescribeCategoryV1Request, opts ...grpc.CallOption) (*DescribeCategoryV1Response, error)
	ListCategoriesV1(ctx context.Context, in *ListCategoriesV1Request, opts ...grpc.CallOption) (*ListCategoriesV1Response, error)
	RemoveCategoryV1(ctx context.Context, in *RemoveCategoryV1Request, opts ...grpc.CallOption) (*RemoveCategoryV1Response, error)
}

type catalogCategoryApiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogCategoryApiServiceClient(cc grpc.ClientConnInterface) CatalogCategoryApiServiceClient {
	return &catalogCategoryApiServiceClient{cc}
}

func (c *catalogCategoryApiServiceClient) CreateCategoryV1(ctx context.Context, in *CreateCategoryV1Request, opts ...grpc.CallOption) (*CreateCategoryV1Response, error) {
	out := new(CreateCategoryV1Response)
	err := c.cc.Invoke(ctx, "/vvvvgross.catalog_category_api.v1.CatalogCategoryApiService/CreateCategoryV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogCategoryApiServiceClient) DescribeCategoryV1(ctx context.Context, in *DescribeCategoryV1Request, opts ...grpc.CallOption) (*DescribeCategoryV1Response, error) {
	out := new(DescribeCategoryV1Response)
	err := c.cc.Invoke(ctx, "/vvvvgross.catalog_category_api.v1.CatalogCategoryApiService/DescribeCategoryV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogCategoryApiServiceClient) ListCategoriesV1(ctx context.Context, in *ListCategoriesV1Request, opts ...grpc.CallOption) (*ListCategoriesV1Response, error) {
	out := new(ListCategoriesV1Response)
	err := c.cc.Invoke(ctx, "/vvvvgross.catalog_category_api.v1.CatalogCategoryApiService/ListCategoriesV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogCategoryApiServiceClient) RemoveCategoryV1(ctx context.Context, in *RemoveCategoryV1Request, opts ...grpc.CallOption) (*RemoveCategoryV1Response, error) {
	out := new(RemoveCategoryV1Response)
	err := c.cc.Invoke(ctx, "/vvvvgross.catalog_category_api.v1.CatalogCategoryApiService/RemoveCategoryV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogCategoryApiServiceServer is the server API for CatalogCategoryApiService service.
// All implementations must embed UnimplementedCatalogCategoryApiServiceServer
// for forward compatibility
type CatalogCategoryApiServiceServer interface {
	CreateCategoryV1(context.Context, *CreateCategoryV1Request) (*CreateCategoryV1Response, error)
	DescribeCategoryV1(context.Context, *DescribeCategoryV1Request) (*DescribeCategoryV1Response, error)
	ListCategoriesV1(context.Context, *ListCategoriesV1Request) (*ListCategoriesV1Response, error)
	RemoveCategoryV1(context.Context, *RemoveCategoryV1Request) (*RemoveCategoryV1Response, error)
	mustEmbedUnimplementedCatalogCategoryApiServiceServer()
}

// UnimplementedCatalogCategoryApiServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCatalogCategoryApiServiceServer struct {
}

func (UnimplementedCatalogCategoryApiServiceServer) CreateCategoryV1(context.Context, *CreateCategoryV1Request) (*CreateCategoryV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCategoryV1 not implemented")
}
func (UnimplementedCatalogCategoryApiServiceServer) DescribeCategoryV1(context.Context, *DescribeCategoryV1Request) (*DescribeCategoryV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeCategoryV1 not implemented")
}
func (UnimplementedCatalogCategoryApiServiceServer) ListCategoriesV1(context.Context, *ListCategoriesV1Request) (*ListCategoriesV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCategoriesV1 not implemented")
}
func (UnimplementedCatalogCategoryApiServiceServer) RemoveCategoryV1(context.Context, *RemoveCategoryV1Request) (*RemoveCategoryV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveCategoryV1 not implemented")
}
func (UnimplementedCatalogCategoryApiServiceServer) mustEmbedUnimplementedCatalogCategoryApiServiceServer() {
}

// UnsafeCatalogCategoryApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogCategoryApiServiceServer will
// result in compilation errors.
type UnsafeCatalogCategoryApiServiceServer interface {
	mustEmbedUnimplementedCatalogCategoryApiServiceServer()
}

func RegisterCatalogCategoryApiServiceServer(s grpc.ServiceRegistrar, srv CatalogCategoryApiServiceServer) {
	s.RegisterService(&CatalogCategoryApiService_ServiceDesc, srv)
}

func _CatalogCategoryApiService_CreateCategoryV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogCategoryApiServiceServer).CreateCategoryV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vvvvgross.catalog_category_api.v1.CatalogCategoryApiService/CreateCategoryV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogCategoryApiServiceServer).CreateCategoryV1(ctx, req.(*CreateCategoryV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogCategoryApiService_DescribeCategoryV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeCategoryV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogCategoryApiServiceServer).DescribeCategoryV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vvvvgross.catalog_category_api.v1.CatalogCategoryApiService/DescribeCategoryV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogCategoryApiServiceServer).DescribeCategoryV1(ctx, req.(*DescribeCategoryV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogCategoryApiService_ListCategoriesV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCategoriesV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogCategoryApiServiceServer).ListCategoriesV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vvvvgross.catalog_category_api.v1.CatalogCategoryApiService/ListCategoriesV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogCategoryApiServiceServer).ListCategoriesV1(ctx, req.(*ListCategoriesV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogCategoryApiService_RemoveCategoryV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCategoryV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogCategoryApiServiceServer).RemoveCategoryV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vvvvgross.catalog_category_api.v1.CatalogCategoryApiService/RemoveCategoryV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogCategoryApiServiceServer).RemoveCategoryV1(ctx, req.(*RemoveCategoryV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogCategoryApiService_ServiceDesc is the grpc.ServiceDesc for CatalogCategoryApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogCategoryApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vvvvgross.catalog_category_api.v1.CatalogCategoryApiService",
	HandlerType: (*CatalogCategoryApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCategoryV1",
			Handler:    _CatalogCategoryApiService_CreateCategoryV1_Handler,
		},
		{
			MethodName: "DescribeCategoryV1",
			Handler:    _CatalogCategoryApiService_DescribeCategoryV1_Handler,
		},
		{
			MethodName: "ListCategoriesV1",
			Handler:    _CatalogCategoryApiService_ListCategoriesV1_Handler,
		},
		{
			MethodName: "RemoveCategoryV1",
			Handler:    _CatalogCategoryApiService_RemoveCategoryV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ozonmp/catalog_category_api/v1/catalog_category_api.proto",
}
